name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Wait for MySQL to be ready
        run: |
          until docker run --rm --network=host mysql:latest mysqladmin ping --silent -h127.0.0.1; do
            echo 'Waiting for MySQL...'
            sleep 5
          done

      - name: Run SQL Scripts
        env:
          MYSQL_HOST: localhost
          MYSQL_PORT: 3306
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        run: |
          for script in $(ls sql-scripts/*.sql); do
            echo "Running $script"
            mysql -h$MYSQL_HOST -P$MYSQL_PORT -u$MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE < $script
          done

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: wyzhaobvt/harmony-server:latest
          build-args: |
            JWT_KEY=${{ secrets.JWT_KEY }}
            SERVER_PORT=${{ secrets.SERVER_PORT }}
            CLIENT_PORT=${{ secrets.CLIENT_PORT }}
            DB_HOST=localhost
            DB_USER=root
            DB_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            DB_NAME=${{ secrets.MYSQL_DATABASE }}

      - name: Deploy Harmony Server
        run: |
          docker run -d --name harmony-server \
            -e JWT_KEY=${{ secrets.JWT_KEY }} \
            -e SERVER_PORT=${{ secrets.SERVER_PORT }} \
            -e CLIENT_PORT=${{ secrets.CLIENT_PORT }} \
            -e DB_HOST=localhost \
            -e DB_USER=root \
            -e DB_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} \
            -e DB_NAME=${{ secrets.MYSQL_DATABASE }} \
            -p 5000:5000 \
            wyzhaobvt/harmony-server:latest
